podman_user: root # String, of the user to become


podman_backup_version: # A simple version control, use a string.
podman_backup_containers: [] # String of containers to backup.

podman_restore_containers: [] # List of podman containers, this will load their images in the format 'container:docker_backup_version'

podman_backup_volumes: [] # List of podman volumes to backup

podman_restore_volumes: [] # List of podman volumes to restore
